const ImageName = {
	Tiles: 'tiles',
	Blood: 'blood',
	Night: 'night',
	MotherTree: 'motherTree',
	Background: 'background',
	GoblinDownRun: 'goblinDownRun',
	GoblinLeftRun: 'goblinLeftRun',
	GoblinRightRun: 'goblinRightRun',
	GoblinUpRun: 'goblinUpRun',
	GoblinDownAttack: 'goblinDownAttack',
	GoblinLeftAttack: 'goblinLeftAttack',
	GoblinRightAttack: 'goblinRightAttack',
	GoblinUpAttack: 'goblinUpAttack',
	WarriorDownRun: 'warriorDownRun',
	WarriorLeftRun: 'warriorLeftRun',
	WarriorRightRun: 'warriorRightRun',
	WarriorUpRun: 'warriorUpRun',
	WarriorDownAttack: 'warriorDownAttack',
	WarriorLeftAttack: 'warriorLeftAttack',
	WarriorRightAttack: 'warriorRightAttack',
	WarriorUpAttack: 'warriorUpAttack',
	SkeletonDownRun: 'skeletonDownRun',
	SkeletonLeftRun: 'skeletonLeftRun',
	SkeletonRightRun: 'skeletonRightRun',
	SkeletonUpRun: 'skeletonUpRun',
	SkeletonDownAttack: 'skeletonDownAttack',
	SkeletonLeftAttack: 'skeletonLeftAttack',
	SkeletonRightAttack: 'skeletonRightAttack',
	SkeletonUpAttack: 'skeletonUpAttack',
};
//skeletonDown
export default ImageName;
